name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip integration
        run: |
          cd custom_components
          zip -r ../ecoflow_delta_pro_ultra.zip ecoflow_delta_pro_ultra/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ecoflow_delta_pro_ultra.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
